import { NextResponse } from 'next/server'
import FeaturedImage1 from '@assets/images/featured-listing-1.png'
import FeaturedImage2 from '@assets/images/featured-listing-2.png'
import FeaturedImage3 from '@assets/images/featured-listing-3.png'

export async function GET() {
  const data = {
    properties: [
      // Original Properties (Enhanced)
      {
        id: 1,
        price: "$2,199",
        title: "Beach Pros Realty", 
        location: "37 Ambleside Gardens, Ilford, IG4 5HH",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [40.719, -74.110], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2019,
        priceValue: 2199,
        slug: 'beach-pros-realty',
        neighborhood: 'Staten Island'
      },
      {
        id: 2,
        price: "$3,599",
        title: "Beacon Homes Realty", 
        location: "3 Leame Close, Hull, HU3 6ND",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage2,
        coordinates: [40.740, -73.986], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2020,
        priceValue: 3599,
        slug: 'beacon-homes-realty',
        neighborhood: 'Financial District'
      },
      {
        id: 3,
        price: "$4,299",
        title: "Downtown Apartment", 
        location: "5th Avenue, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [40.760, -73.880],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4299,
        slug: 'downtown-apartment',
        neighborhood: 'Manhattan'
      },
      {
        id: 4,
        price: "$4,299",
        title: "Brooklyn Studio", 
        location: "Brooklyn Heights, NY",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [40.773, -73.950], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2018,
        priceValue: 4299,
        slug: 'brooklyn-studio',
        neighborhood: 'Brooklyn Heights'
      },
      {
        id: 5,
        price: "$5,099",
        title: "Herringbone Realty", 
        location: "28B Highgate Road, London, NW5 1NS",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage2,
        coordinates: [40.758, -74.072], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2022,
        priceValue: 5099,
        slug: 'herringbone-realty',
        neighborhood: 'New Jersey'
      },
      {
        id: 6,
        price: "$1,299",
        title: "Greenwich Loft", 
        location: "Greenwich Village, NY",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [40.743, -73.928], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 1299,
        slug: 'greenwich-loft',
        neighborhood: 'Greenwich Village'
      },
      {
        id: 7,
        price: "$3,899",
        title: "Chelsea Apartment", 
        location: "Chelsea, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [40.747, -74.002], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 3899,
        slug: 'chelsea-apartment',
        neighborhood: 'Chelsea'
      },
      {
        id: 8,
        price: "$2,599",
        title: "West Side Studio", 
        location: "Upper West Side, NY",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage2,
        coordinates: [40.785, -73.978], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2019,
        priceValue: 2599,
        slug: 'west-side-studio',
        neighborhood: 'Upper West Side'
      },
      {
        id: 9,
        price: "$4,799",
        title: "Tribeca Penthouse", 
        location: "Tribeca, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage3,
        coordinates: [40.719, -74.009], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 4799,
        slug: 'tribeca-penthouse',
        neighborhood: 'Tribeca'
      },

      // New Properties - More Variety (Rentals)
      {
        id: 10,
        price: "$1,899",
        title: "Cozy East Village Studio",
        location: "East Village, Manhattan, NY",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [40.728, -73.986],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2016,
        priceValue: 1899,
        slug: 'cozy-east-village-studio',
        neighborhood: 'East Village'
      },
      {
        id: 11,
        price: "$3,299",
        title: "Modern SoHo Loft",
        location: "SoHo, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [40.723, -74.002],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2018,
        priceValue: 3299,
        slug: 'modern-soho-loft',
        neighborhood: 'SoHo'
      },
      {
        id: 12,
        price: "$4,599",
        title: "Luxury Murray Hill Apartment",
        location: "Murray Hill, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [40.748, -73.979],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4599,
        slug: 'luxury-murray-hill-apartment',
        neighborhood: 'Murray Hill'
      },
      {
        id: 13,
        price: "$2,799",
        title: "Williamsburg Studio",
        location: "Williamsburg, Brooklyn, NY",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage1,
        coordinates: [40.714, -73.957],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2019,
        priceValue: 2799,
        slug: 'williamsburg-studio',
        neighborhood: 'Williamsburg'
      },
      {
        id: 14,
        price: "$5,299",
        title: "Premium Financial District Penthouse",
        location: "Financial District, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [40.708, -74.011],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2022,
        priceValue: 5299,
        slug: 'premium-financial-district-penthouse',
        neighborhood: 'Financial District'
      },

      // For Sale Properties
      {
        id: 15,
        price: "$899,000",
        title: "Upper East Side Condo",
        location: "Upper East Side, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [40.768, -73.957],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 899000,
        slug: 'upper-east-side-condo',
        neighborhood: 'Upper East Side'
      },
      {
        id: 16,
        price: "$1,250,000",
        title: "Brooklyn Heights Townhouse",
        location: "Brooklyn Heights, Brooklyn, NY",
        beds: 3,
        baths: 3,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [40.695, -73.993],
        isMonthly: false,
        type: 'sale' as const,
        category: 'realty',
        yearBuilt: 2019,
        priceValue: 1250000,
        slug: 'brooklyn-heights-townhouse',
        neighborhood: 'Brooklyn Heights'
      },
      {
        id: 17,
        price: "$750,000",
        title: "Midtown West Loft",
        location: "Midtown West, Manhattan, NY",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [40.758, -73.989],
        isMonthly: false,
        type: 'sale' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 750000,
        slug: 'midtown-west-loft',
        neighborhood: 'Midtown West'
      },
      {
        id: 18,
        price: "$2,100,000",
        title: "Central Park West Penthouse",
        location: "Central Park West, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage3,
        coordinates: [40.776, -73.975],
        isMonthly: false,
        type: 'sale' as const,
        category: 'penthouse',
        yearBuilt: 2024,
        priceValue: 2100000,
        slug: 'central-park-west-penthouse',
        neighborhood: 'Central Park West'
      },
      {
        id: 19,
        price: "$450,000",
        title: "Compact East Harlem Studio",
        location: "East Harlem, Manhattan, NY",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [40.793, -73.943],
        isMonthly: false,
        type: 'sale' as const,
        category: 'studio',
        yearBuilt: 2015,
        priceValue: 450000,
        slug: 'compact-east-harlem-studio',
        neighborhood: 'East Harlem'
      },

      // More Rentals - Different Price Ranges
      {
        id: 20,
        price: "$1,599",
        title: "Budget-Friendly Queens Studio",
        location: "Long Island City, Queens, NY",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage2,
        coordinates: [40.744, -73.948],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2016,
        priceValue: 1599,
        slug: 'budget-friendly-queens-studio',
        neighborhood: 'Long Island City'
      },
      {
        id: 21,
        price: "$3,799",
        title: "Trendy Dumbo Loft",
        location: "Dumbo, Brooklyn, NY",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [40.703, -73.989],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2020,
        priceValue: 3799,
        slug: 'trendy-dumbo-loft',
        neighborhood: 'Dumbo'
      },
      {
        id: 22,
        price: "$4,899",
        title: "High-End NoMad Apartment",
        location: "NoMad, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [40.744, -73.988],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2022,
        priceValue: 4899,
        slug: 'high-end-nomad-apartment',
        neighborhood: 'NoMad'
      },
      {
        id: 23,
        price: "$6,299",
        title: "Luxury Times Square Penthouse",
        location: "Times Square, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [40.758, -73.985],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 6299,
        slug: 'luxury-times-square-penthouse',
        neighborhood: 'Times Square'
      },
      {
        id: 24,
        price: "$2,899",
        title: "Charming Park Slope Apartment",
        location: "Park Slope, Brooklyn, NY",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [40.672, -73.977],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2018,
        priceValue: 2899,
        slug: 'charming-park-slope-apartment',
        neighborhood: 'Park Slope'
      },

      // More For Sale Properties
      {
        id: 25,
        price: "$1,450,000",
        title: "Spacious Chelsea Condo",
        location: "Chelsea, Manhattan, NY",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [40.746, -74.004],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 1450000,
        slug: 'spacious-chelsea-condo',
        neighborhood: 'Chelsea'
      },
      {
        id: 26,
        price: "$680,000",
        title: "Renovated Lower East Side Loft",
        location: "Lower East Side, Manhattan, NY",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [40.715, -73.987],
        isMonthly: false,
        type: 'sale' as const,
        category: 'loft',
        yearBuilt: 2016,
        priceValue: 680000,
        slug: 'renovated-lower-east-side-loft',
        neighborhood: 'Lower East Side'
      },
      {
        id: 27,
        price: "$1,850,000",
        title: "Elite Gramercy Realty",
        location: "Gramercy, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "5x7 m²",
        image: FeaturedImage3,
        coordinates: [40.738, -73.984],
        isMonthly: false,
        type: 'sale' as const,
        category: 'realty',
        yearBuilt: 2022,
        priceValue: 1850000,
        slug: 'elite-gramercy-realty',
        neighborhood: 'Gramercy'
      },
      {
        id: 28,
        price: "$950,000",
        title: "Modern Flatiron Apartment",
        location: "Flatiron, Manhattan, NY",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [40.741, -73.989],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2019,
        priceValue: 950000,
        slug: 'modern-flatiron-apartment',
        neighborhood: 'Flatiron'
      },
      {
        id: 29,
        price: "$3,200,000",
        title: "Exclusive TriBeCa Penthouse",
        location: "TriBeCa, Manhattan, NY",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [40.716, -74.007],
        isMonthly: false,
        type: 'sale' as const,
        category: 'penthouse',
        yearBuilt: 2024,
        priceValue: 3200000,
        slug: 'exclusive-tribeca-penthouse',
        neighborhood: 'TriBeCa'
      },

      // Edge Cases - Different Years & Sizes
      {
        id: 30,
        price: "$1,799",
        title: "Vintage East Village Apartment",
        location: "East Village, Manhattan, NY",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage3,
        coordinates: [40.726, -73.984],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2015,
        priceValue: 1799,
        slug: 'vintage-east-village-apartment',
        neighborhood: 'East Village'
      }
    ]
  }

  return NextResponse.json(data)
}
