import { NextResponse } from 'next/server'
import FeaturedImage1 from '@assets/images/featured-listing-1.png'
import FeaturedImage2 from '@assets/images/featured-listing-2.png'
import FeaturedImage3 from '@assets/images/featured-listing-3.png'

export async function GET() {
  const data = {
    properties: [
      // California, US Properties
      {
        id: 1,
        price: "$2,199",
        title: "Beach Pros Realty", 
        location: "Santa Monica, California, US",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [34.0195, -118.4912], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2019,
        priceValue: 2199,
        slug: 'beach-pros-realty',
        neighborhood: 'Santa Monica'
      },
      {
        id: 2,
        price: "$3,599",
        title: "Beacon Homes Realty", 
        location: "San Francisco, California, US",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage2,
        coordinates: [37.7749, -122.4194], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2020,
        priceValue: 3599,
        slug: 'beacon-homes-realty',
        neighborhood: 'Financial District'
      },
      {
        id: 3,
        price: "$4,299",
        title: "Downtown Apartment", 
        location: "Los Angeles, California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [34.0522, -118.2437],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4299,
        slug: 'downtown-apartment',
        neighborhood: 'Downtown LA'
      },
      {
        id: 4,
        price: "$4,299",
        title: "Brooklyn Studio", 
        location: "San Diego, California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [32.7157, -117.1611], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2018,
        priceValue: 4299,
        slug: 'brooklyn-studio',
        neighborhood: 'Gaslamp Quarter'
      },
      {
        id: 5,
        price: "$5,099",
        title: "Herringbone Realty", 
        location: "London, UK",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage2,
        coordinates: [51.5080, -0.1247], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2022,
        priceValue: 5099,
        slug: 'herringbone-realty',
        neighborhood: 'Westminster'
      },
      {
        id: 6,
        price: "$1,299",
        title: "Greenwich Loft", 
        location: "London, UK",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [51.4783, -0.0007], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 1299,
        slug: 'greenwich-loft',
        neighborhood: 'Greenwich'
      },
      {
        id: 7,
        price: "$3,899",
        title: "Chelsea Apartment", 
        location: "London, UK",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [51.4869, -0.1657], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 3899,
        slug: 'chelsea-apartment',
        neighborhood: 'Chelsea'
      },
      {
        id: 8,
        price: "$2,599",
        title: "West Side Studio", 
        location: "Milan, Italia",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage2,
        coordinates: [45.4612, 9.1947], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2019,
        priceValue: 2599,
        slug: 'west-side-studio',
        neighborhood: 'Brera'
      },
      {
        id: 9,
        price: "$4,799",
        title: "Tribeca Penthouse", 
        location: "Milan, Italia",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage3,
        coordinates: [45.4677, 9.1811], 
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 4799,
        slug: 'tribeca-penthouse',
        neighborhood: 'Duomo'
      },

      // Barcelona, Spain Properties
      {
        id: 10,
        price: "$1,899",
        title: "Cozy East Village Studio",
        location: "Barcelona, Spain",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [41.3890, 2.1720],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2016,
        priceValue: 1899,
        slug: 'cozy-east-village-studio',
        neighborhood: 'Gothic Quarter'
      },
      {
        id: 11,
        price: "$3,299",
        title: "Modern SoHo Loft",
        location: "Barcelona, Spain",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [41.4040, 2.1997],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2018,
        priceValue: 3299,
        slug: 'modern-soho-loft',
        neighborhood: 'Eixample'
      },
      {
        id: 12,
        price: "$4,599",
        title: "Luxury Murray Hill Apartment",
        location: "Barcelona, Spain",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [41.4013, 2.1621],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4599,
        slug: 'luxury-murray-hill-apartment',
        neighborhood: 'Gracia'
      },
      {
        id: 13,
        price: "$2,799",
        title: "Williamsburg Studio",
        location: "Barcelona, Spain",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage1,
        coordinates: [41.3815, 2.1206],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2019,
        priceValue: 2799,
        slug: 'williamsburg-studio',
        neighborhood: 'Poble Sec'
      },
      {
        id: 14,
        price: "$5,299",
        title: "Premium Financial District Penthouse",
        location: "Barcelona, Spain",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [41.3986, 2.1646],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2022,
        priceValue: 5299,
        slug: 'premium-financial-district-penthouse',
        neighborhood: 'Passeig de Gracia'
      },

      // For Sale Properties - California, US
      {
        id: 15,
        price: "$899,000",
        title: "Upper East Side Condo",
        location: "San Francisco, California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [37.7849, -122.4094],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 899000,
        slug: 'upper-east-side-condo',
        neighborhood: 'Mission District'
      },
      {
        id: 16,
        price: "$1,250,000",
        title: "Brooklyn Heights Townhouse",
        location: "Los Angeles, California, US",
        beds: 3,
        baths: 3,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [34.0736, -118.4004],
        isMonthly: false,
        type: 'sale' as const,
        category: 'realty',
        yearBuilt: 2019,
        priceValue: 1250000,
        slug: 'brooklyn-heights-townhouse',
        neighborhood: 'Beverly Hills'
      },
      {
        id: 17,
        price: "$750,000",
        title: "Midtown West Loft",
        location: "San Diego, California, US",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [32.7073, -117.1566],
        isMonthly: false,
        type: 'sale' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 750000,
        slug: 'midtown-west-loft',
        neighborhood: 'Little Italy'
      },
      {
        id: 18,
        price: "$2,100,000",
        title: "Central Park West Penthouse",
        location: "Santa Monica, California, US",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage3,
        coordinates: [34.0119, -118.4949],
        isMonthly: false,
        type: 'sale' as const,
        category: 'penthouse',
        yearBuilt: 2024,
        priceValue: 2100000,
        slug: 'central-park-west-penthouse',
        neighborhood: 'Malibu'
      },
      {
        id: 19,
        price: "$450,000",
        title: "Compact East Harlem Studio",
        location: "London, UK",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [51.5248, -0.0998],
        isMonthly: false,
        type: 'sale' as const,
        category: 'studio',
        yearBuilt: 2015,
        priceValue: 450000,
        slug: 'compact-east-harlem-studio',
        neighborhood: 'Shoreditch'
      },

      // More Rentals - Milan, Italia
      {
        id: 20,
        price: "$1,599",
        title: "Budget-Friendly Queens Studio",
        location: "Milan, Italia",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage2,
        coordinates: [45.4578, 9.1785],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2016,
        priceValue: 1599,
        slug: 'budget-friendly-queens-studio',
        neighborhood: 'Navigli'
      },
      {
        id: 21,
        price: "$3,799",
        title: "Trendy Dumbo Loft",
        location: "Milan, Italia",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [45.4749, 9.1878],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2020,
        priceValue: 3799,
        slug: 'trendy-dumbo-loft',
        neighborhood: 'Porta Nuova'
      },
      {
        id: 22,
        price: "$4,899",
        title: "High-End NoMad Apartment",
        location: "Milan, Italia",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [45.4698, 9.1983],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2022,
        priceValue: 4899,
        slug: 'high-end-nomad-apartment',
        neighborhood: 'Quadrilatero della Moda'
      },
      {
        id: 23,
        price: "$6,299",
        title: "Luxury Times Square Penthouse",
        location: "Milan, Italia",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [45.4605, 9.1741],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 6299,
        slug: 'luxury-times-square-penthouse',
        neighborhood: 'Duomo'
      },
      {
        id: 24,
        price: "$2,899",
        title: "Charming Park Slope Apartment",
        location: "Milan, Italia",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [45.4610, 9.1881],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2018,
        priceValue: 2899,
        slug: 'charming-park-slope-apartment',
        neighborhood: 'Corso Buenos Aires'
      },

      // More For Sale Properties - London, UK
      {
        id: 25,
        price: "$1,450,000",
        title: "Spacious Chelsea Condo",
        location: "London, UK",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage1,
        coordinates: [51.5174, -0.1445],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 1450000,
        slug: 'spacious-chelsea-condo',
        neighborhood: 'Chelsea'
      },
      {
        id: 26,
        price: "$680,000",
        title: "Renovated Lower East Side Loft",
        location: "London, UK",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [51.4986, -0.1463],
        isMonthly: false,
        type: 'sale' as const,
        category: 'loft',
        yearBuilt: 2016,
        priceValue: 680000,
        slug: 'renovated-lower-east-side-loft',
        neighborhood: 'Shoreditch'
      },
      {
        id: 27,
        price: "$1,850,000",
        title: "Elite Gramercy Realty",
        location: "London, UK",
        beds: 3,
        baths: 3,
        area: "5x7 m²",
        image: FeaturedImage3,
        coordinates: [51.5122, -0.1287],
        isMonthly: false,
        type: 'sale' as const,
        category: 'realty',
        yearBuilt: 2022,
        priceValue: 1850000,
        slug: 'elite-gramercy-realty',
        neighborhood: 'Westminster'
      },
      {
        id: 28,
        price: "$950,000",
        title: "Modern Flatiron Apartment",
        location: "London, UK",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [51.4789, 0.0011],
        isMonthly: false,
        type: 'sale' as const,
        category: 'apartment',
        yearBuilt: 2019,
        priceValue: 950000,
        slug: 'modern-flatiron-apartment',
        neighborhood: 'Covent Garden'
      },
      {
        id: 29,
        price: "$3,200,000",
        title: "Exclusive TriBeCa Penthouse",
        location: "London, UK",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [51.4914, -0.1673],
        isMonthly: false,
        type: 'sale' as const,
        category: 'penthouse',
        yearBuilt: 2024,
        priceValue: 3200000,
        slug: 'exclusive-tribeca-penthouse',
        neighborhood: 'Mayfair'
      },

      // Edge Cases - Different Years & Sizes - Barcelona, Spain
      {
        id: 30,
        price: "$1,799",
        title: "Vintage East Village Apartment",
        location: "Barcelona, Spain",
        beds: 1,
        baths: 1,
        area: "3x5 m²",
        image: FeaturedImage3,
        coordinates: [41.3836, 2.1730],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2015,
        priceValue: 1799,
        slug: 'vintage-east-village-apartment',
        neighborhood: 'Poble Sec'
      },

      // Additional Properties for Pagination Testing (31-50) - California, US
      {
        id: 31,
        price: "$2,199",
        title: "Modern Hell's Kitchen Studio",
        location: "San Francisco, California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [37.7849, -122.4094],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2020,
        priceValue: 2199,
        slug: 'modern-hells-kitchen-studio',
        neighborhood: 'Mission District'
      },
      {
        id: 32,
        price: "$3,599",
        title: "Spacious Upper Manhattan Apartment",
        location: "Los Angeles, California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage2,
        coordinates: [34.0736, -118.4004],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2019,
        priceValue: 3599,
        slug: 'spacious-upper-manhattan-apartment',
        neighborhood: 'Hollywood'
      },
      {
        id: 33,
        price: "$4,299",
        title: "Luxury Battery Park City Condo",
        location: "San Diego, California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [32.7073, -117.1566],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4299,
        slug: 'luxury-battery-park-city-condo',
        neighborhood: 'Downtown San Diego'
      },
      {
        id: 34,
        price: "$1,899",
        title: "Cozy Astoria Studio",
        location: "Santa Monica, California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [34.0119, -118.4949],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2017,
        priceValue: 1899,
        slug: 'cozy-astoria-studio',
        neighborhood: 'Venice Beach'
      },
      {
        id: 35,
        price: "$5,099",
        title: "Premium Upper West Side Penthouse",
        location: "San Francisco, California, US",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [37.7749, -122.4194],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2022,
        priceValue: 5099,
        slug: 'premium-upper-west-side-penthouse',
        neighborhood: 'Financial District'
      },
      {
        id: 36,
        price: "$2,599",
        title: "Trendy Bushwick Loft",
        location: "London, UK",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [51.5155, -0.0977],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2018,
        priceValue: 2599,
        slug: 'trendy-bushwick-loft',
        neighborhood: 'Shoreditch'
      },
      {
        id: 37,
        price: "$3,299",
        title: "Modern Crown Heights Apartment",
        location: "California, US",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage1,
        coordinates: [34.0203, -118.4936],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 3299,
        slug: 'modern-crown-heights-apartment',
        neighborhood: 'Santa Monica'
      },
      {
        id: 38,
        price: "$4,799",
        title: "Elite Sutton Place Realty",
        location: "California, US",
        beds: 3,
        baths: 2,
        area: "5x7 m²",
        image: FeaturedImage2,
        coordinates: [37.7751, -122.4168],
        isMonthly: true,
        type: 'rent' as const,
        category: 'realty',
        yearBuilt: 2021,
        priceValue: 4799,
        slug: 'elite-sutton-place-realty',
        neighborhood: 'Financial District'
      },
      {
        id: 39,
        price: "$1,599",
        title: "Affordable Sunset Park Studio",
        location: "California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage3,
        coordinates: [34.0484, -118.2437],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2016,
        priceValue: 1599,
        slug: 'affordable-sunset-park-studio',
        neighborhood: 'Downtown LA'
      },
      {
        id: 40,
        price: "$3,899",
        title: "Chic Prospect Heights Apartment",
        location: "California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [32.7158, -117.1566],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2019,
        priceValue: 3899,
        slug: 'chic-prospect-heights-apartment',
        neighborhood: 'Gaslamp Quarter'
      },
      {
        id: 41,
        price: "$6,299",
        title: "Luxury SoHo Penthouse",
        location: "California, US",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [34.0100, -118.4905],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 6299,
        slug: 'luxury-soho-penthouse',
        neighborhood: 'Mission District'
      },
      {
        id: 42,
        price: "$2,299",
        title: "Modern Bay Ridge Loft",
        location: "California, US",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage3,
        coordinates: [37.7882, -122.4118],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 2299,
        slug: 'modern-bay-ridge-loft',
        neighborhood: 'Hollywood'
      },
      {
        id: 43,
        price: "$4,199",
        title: "Elegant Yorkville Apartment",
        location: "California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage1,
        coordinates: [34.0729, -118.4014],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2020,
        priceValue: 4199,
        slug: 'elegant-yorkville-apartment',
        neighborhood: 'Venice Beach'
      },
      {
        id: 44,
        price: "$1,799",
        title: "Cozy Ridgewood Studio",
        location: "California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage2,
        coordinates: [32.7099, -117.1542],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2018,
        priceValue: 1799,
        slug: 'cozy-ridgewood-studio',
        neighborhood: 'Beverly Hills'
      },
      {
        id: 45,
        price: "$5,599",
        title: "Premium Lincoln Center Penthouse",
        location: "California, US",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage3,
        coordinates: [34.0778, -118.3997],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2022,
        priceValue: 5599,
        slug: 'premium-lincoln-center-penthouse',
        neighborhood: 'Malibu'
      },
      {
        id: 46,
        price: "$3,099",
        title: "Modern Red Hook Apartment",
        location: "California, US",
        beds: 2,
        baths: 2,
        area: "4x5 m²",
        image: FeaturedImage1,
        coordinates: [34.0084, -118.4962],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2019,
        priceValue: 3099,
        slug: 'modern-red-hook-apartment',
        neighborhood: 'Little Italy'
      },
      {
        id: 47,
        price: "$2,799",
        title: "Trendy Greenpoint Loft",
        location: "California, US",
        beds: 2,
        baths: 1,
        area: "4x5 m²",
        image: FeaturedImage2,
        coordinates: [37.7893, -122.4047],
        isMonthly: true,
        type: 'rent' as const,
        category: 'loft',
        yearBuilt: 2017,
        priceValue: 2799,
        slug: 'trendy-greenpoint-loft',
        neighborhood: 'Santa Monica'
      },
      {
        id: 48,
        price: "$4,499",
        title: "Luxury Kips Bay Apartment",
        location: "California, US",
        beds: 2,
        baths: 2,
        area: "4x6 m²",
        image: FeaturedImage3,
        coordinates: [34.0565, -118.2403],
        isMonthly: true,
        type: 'rent' as const,
        category: 'apartment',
        yearBuilt: 2021,
        priceValue: 4499,
        slug: 'luxury-kips-bay-apartment',
        neighborhood: 'Financial District'
      },
      {
        id: 49,
        price: "$1,999",
        title: "Charming Forest Hills Studio",
        location: "California, US",
        beds: 1,
        baths: 1,
        area: "3x4 m²",
        image: FeaturedImage1,
        coordinates: [32.7164, -117.1656],
        isMonthly: true,
        type: 'rent' as const,
        category: 'studio',
        yearBuilt: 2018,
        priceValue: 1999,
        slug: 'charming-forest-hills-studio',
        neighborhood: 'Downtown LA'
      },
      {
        id: 50,
        price: "$5,899",
        title: "Exclusive Union Square Penthouse",
        location: "California, US",
        beds: 3,
        baths: 3,
        area: "6x8 m²",
        image: FeaturedImage2,
        coordinates: [34.0219, -118.4899],
        isMonthly: true,
        type: 'rent' as const,
        category: 'penthouse',
        yearBuilt: 2023,
        priceValue: 5899,
        slug: 'exclusive-union-square-penthouse',
        neighborhood: 'Gaslamp Quarter'
      },

    ]
  }

  return NextResponse.json(data)
}
